name: example
description: Charts-Flutter Demo
environment:
  sdk: '>=2.12.0 <4.0.0'
  # flutter: '>=2.5.0'

dependencies:
  charts_flutter:
    path: ../
  cupertino_icons: 
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.15.0
  intl: ^0.19.0
flutter:
  uses-material-design: true
