name: charts_common
version: 0.13.0
description: A common library for charting packages.
homepage: https://github.com/google/charts

environment:
  sdk: '>=3.0.0<=4.0.0'

dependencies:
  collection: ^1.14.5
  intl: ^0.19.0
  vector_math: ^2.0.8
  logging: ^1.2.0
  meta: ^1.12.0

dev_dependencies:
  mockito: ^5.3.2
  test: ^1.25.2
