name: charts_flutter
version: 0.12.0
description: Material Design charting library for flutter.
homepage: https://github.com/google/charts

environment:
  sdk: '>=2.19.6<=4.0.0'
#  flutter: '>=2.5.0'

dependencies:
  # Pointing this to a local path allows for pointing to the latest code
  # in Github for open source development.
  #
  # The pub version of charts_flutter will point to the pub version of charts_common.
  # The latest pub version is commented out and shown below as an example.
  #charts_common: ^0.12.0
  
  # charts_common:
  #   path: ../charts_common/
  charts_common:
    git: 
      url: https://github.com/marcosgianetti/charts.git
      ref: master
      path: charts_common
  collection: ^1.14.5
  flutter:
    sdk: flutter
  intl: ^0.19.0
  logging: ^1.2.0
  meta: 1.12.0


dev_dependencies:
  mockito: 
  build_runner: 
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.25.2
